### ISSUE TITLE
absl flagfile adding into args.py

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [theblackcat102/Online-Speech-Recognition#37]
Hi, i wants to add the flagfile into python file so that i dont have to pass commandline arguments to python file any idea how to do it ?

**Comment by Drwaish** [comment]
Dear Community, if you want to run without adding flagfiles in command line argument, copy model hyper-parameters from .txt  files into rnnt/args.py. In  this way, model load parameters from args.py instead of .txt file while running.
