### ISSUE TITLE
zh training flagfile

### ISSUE THREAD

**Issue by ccc0117** [theblackcat102/Online-Speech-Recognition#38]
Hi,
I got the zh_70_medium pretrined model from v1.
Could I ask about the training flagfile and waht training data is uesd ?
Thank you very much!

**Comment by theblackcat102** [comment]
Hi @ccc0117,

The flagfile for zh_70_medium can be found [here](https://github.com/theblackcat102/edgedict/blob/master/flagfiles/E6D2_LARGE_Batch.txt)
The training data are mainly consist of mozilla common voice and youtube chinese caption
